// should be generated by a preprocessor

// import class file
import { ConverterTest } from "./examples/Basic";

// decorated class
const basic = new ConverterTest();
const te = basic.convert.test;

// decorated method
const expected = te.call(basic, ...te.defaults);
const got = basic.convert(...te.defaults);
console.log(expected, "==", got)

// decorated method
const tx = basic.net.test;

const a = tx.call(basic, ...tx.defaults);
const b = basic.net(...tx.defaults)
console.log(a, "==", b)


////////////////////////////

import { ConverterTest1 } from "./examples/Basic";

// decorated class
const test1 = new ConverterTest1();
const t = test1.convert.test;

// decorated method
const x = t.call(test1, ...t.defaults);
const y = test1.convert(...t.defaults);
console.log(x, "==", y)

////////////////////////////

// import class file
import { ConverterTest2 } from "./examples/Basic";

// decorated class
const test = new ConverterTest2();
const tests = test.convert.test;

// decorated method
const c = tests.call(test, ...tests.defaults);
const d = test.convert(...tests.defaults);
console.log(c, "==", d)
